import type { Exercise, MetricDefinition } from '@/types/analysis';

export const METRIC_CATALOG: MetricDefinition[] = [
  {
    id: 'face_symmetry',
    label: 'Gesichtssymmetrie',
    category: 'symmetry',
    description: 'Gesamte Links-Rechts-Balance der Gesichtslandmarken.',
    howMeasured: 'Vergleich spiegelbildlicher Landmark-Paare relativ zur Gesichtsmitte.',
    whyImportant: 'Kleine Asymmetrien sind normal; starke Abweichungen fallen in Fotos stärker auf.',
    normRange: '80–95 % bei den meisten Gesichtern',
    unit: '%',
  },
  {
    id: 'golden_ratio',
    label: 'Golden Ratio',
    category: 'proportions',
    description: 'Annäherung an klassische Proportionsverhältnisse (φ ≈ 1,618).',
    howMeasured: 'Verhältnisse ausgewählter vertikaler und horizontaler Gesichtsabstände.',
    whyImportant: 'Ein Orientierungsmaß für Proportionen – kein Schönheitsurteil.',
    normRange: 'φ-Nähe ±8 %',
    unit: 'φ',
  },
  {
    id: 'facial_thirds',
    label: 'Facial Thirds',
    category: 'proportions',
    description: 'Gleichgewicht von Stirn-, Mittel- und Untergesicht.',
    howMeasured: 'Drei vertikale Segmente: Haaransatz–Brauen, Brauen–Nasenbasis, Nasenbasis–Kinn.',
    whyImportant: 'Ungleiche Drittel beeinflussen die wahrgenommene Gesichtsbalance.',
    normRange: 'nahezu 1:1:1',
    unit: 'balance',
  },
  {
    id: 'facial_fifths',
    label: 'Facial Fifths',
    category: 'proportions',
    description: 'Horizontale Fünftelung der Gesichtsbreite.',
    howMeasured: 'Augeninnen-/außenkanten und Gesichtsseiten als fünf Segmente.',
    whyImportant: 'Hilft, Augen- und Nasenbreite im Kontext der Gesichtswweite zu bewerten.',
    normRange: 'nahezu gleichmäßige Fünftel',
    unit: 'balance',
  },
  {
    id: 'eye_height',
    label: 'Augenhöhe',
    category: 'features',
    description: 'Höhensymmetrie der Augenachsen.',
    howMeasured: 'Vertikale Differenz der Pupillenmittelpunkte.',
    whyImportant: 'Höhendifferenzen können den Ausdruck asymmetrisch wirken lassen.',
    normRange: '< 2 mm Abweichung',
    unit: 'mm Δ',
  },
  {
    id: 'eye_spacing',
    label: 'Augenabstand',
    category: 'features',
    description: 'Interpupillardistanz relativ zur Gesichtsbreite.',
    howMeasured: 'Abstand der Pupillen / Jochbeinbreite.',
    whyImportant: 'Zentrales Proportionselement im oberen Gesicht.',
    normRange: '0,44–0,48',
    unit: 'ratio',
  },
  {
    id: 'eye_angle',
    label: 'Augenwinkel',
    category: 'features',
    description: 'Symmetrie der inneren und äußeren Augenwinkel.',
    howMeasured: 'Winkelvergleich linker und rechter Lidspalte.',
    whyImportant: 'Beeinflusst den Blick und die Augenform-Wahrnehmung.',
    normRange: '±1,5°',
    unit: '°',
  },
  {
    id: 'jaw_angle',
    label: 'Kieferwinkel',
    category: 'profile',
    description: 'Winkel und Definition der Kieferwinkel aus Frontal- und Seitenansicht.',
    howMeasured: '360°-Scan: Vergleich linker/rechter Gonion-Winkel und Kontur.',
    whyImportant: 'Beeinflusst die untere Gesichtsstruktur – stark lichtabhängig.',
    normRange: 'symmetrische Winkel ±3°',
    unit: '°',
  },
  {
    id: 'face_width',
    label: 'Gesichtsbreite',
    category: 'proportions',
    description: 'Bizygomatische Breite relativ zur Gesichtshöhe.',
    howMeasured: 'Jochbeinbreite / Gesichtshöhe aus Frontalframe.',
    whyImportant: 'Grundlage für fWHR und Gesichtsform.',
    normRange: 'individuell, proportional zur Höhe',
    unit: 'ratio',
  },
  {
    id: 'face_depth',
    label: 'Gesichtstiefe',
    category: 'profile',
    description: 'Geschätzte Tiefenwirkung aus seitlichen Scan-Frames.',
    howMeasured: '360°-Scan: relative Projektion von Stirn, Nase, Lippen, Kinn.',
    whyImportant: 'Nur mit Mehrwinkel-Scan sinnvoll schätzbar.',
    normRange: 'ausgewogene Profilkette',
    unit: 'score',
  },
  {
    id: 'side_profile',
    label: 'Seitliches Profil',
    category: 'profile',
    description: 'Harmonie der Seitenansicht aus dem 360°-Scan.',
    howMeasured: 'Frames links/rechts: Stirn–Nase–Lippen–Kinn-Linie.',
    whyImportant: 'Profil wirkt oft anders als die Frontalansicht.',
    normRange: 'ausgeglichene Silhouette',
    unit: 'score',
  },
  {
    id: 'nose_profile',
    label: 'Nasenprofil',
    category: 'profile',
    description: 'Nasenspitze, Rücken und Projektion im Profil.',
    howMeasured: 'Seitenframes des 360°-Scans.',
    whyImportant: 'Stark individueller Wert – kein Idealmaß.',
    normRange: 'natürliche Variation',
    unit: 'score',
  },
  {
    id: 'posture_head',
    label: 'Kopfhaltung',
    category: 'profile',
    description: 'Kopf- und Nackenhaltung während des Scans.',
    howMeasured: 'Neigung und Vorlage über alle Scan-Posen.',
    whyImportant: 'Haltung beeinflusst Jawline- und Kinnwirkung stark.',
    normRange: 'neutrale, aufrechte Haltung',
    unit: 'score',
  },
  {
    id: 'mandible',
    label: 'Unterkiefer',
    category: 'profile',
    description: 'Kontur und Balance des Unterkiefers.',
    howMeasured: 'Frontal + Seitenframes: Unterkieferlinie.',
    whyImportant: 'Teil der Jawline- und Kinnanalyse.',
    normRange: 'klare, weiche Kontur unter gutem Licht',
    unit: 'score',
  },
  {
    id: 'maxilla',
    label: 'Oberkiefer',
    category: 'profile',
    description: 'Midface-Unterstützung / Oberkieferprojektion (geschätzt).',
    howMeasured: '360°-Scan: relative Midface-Tiefe.',
    whyImportant: 'Beeinflusst Nasen- und Lippenlage im Profil.',
    normRange: 'orientierend, kein klinisches Maß',
    unit: 'score',
  },
  {
    id: 'neckline',
    label: 'Halslinie',
    category: 'profile',
    description: 'Übergang Kinn–Hals unter Scan-Licht.',
    howMeasured: 'Unteres Frame bei Center/Down-Posen.',
    whyImportant: 'Foto- und haltungsabhängig.',
    normRange: 'weicher Übergang ohne starke Schatten',
    unit: 'score',
  },
  {
    id: 'canthal_tilt',
    label: 'Canthal Tilt',
    category: 'features',
    description: 'Neigung der Lidspalte vom inneren zum äußeren Augenwinkel.',
    howMeasured: 'Winkel der Lidachsenlinie relativ zur Horizontalen.',
    whyImportant: 'Häufig diskutiertes Merkmal – Werte streuen natürlich stark.',
    normRange: 'ca. +2° bis +8° (individuell)',
    unit: '°',
  },
  {
    id: 'eyebrows',
    label: 'Augenbrauen',
    category: 'features',
    description: 'Höhe, Winkel und Symmetrie der Brauenbögen.',
    howMeasured: 'Landmarken an Brauenanfang, -höhepunkt und -ende.',
    whyImportant: 'Brauen rahmen die Augen und steuern den Ausdruck.',
    normRange: 'hohe Links-Rechts-Ähnlichkeit',
    unit: '%',
  },
  {
    id: 'forehead',
    label: 'Stirn',
    category: 'features',
    description: 'Stirnhöhe und -breite im oberen Gesichtsdrittel.',
    howMeasured: 'Haaransatz bis Brauenlinie und Stirnbreite vs. Jochbein.',
    whyImportant: 'Teil der Facial Thirds und der Gesichtsform.',
    normRange: 'ca. 30–36 % der Gesichtshöhe',
    unit: 'ratio',
  },
  {
    id: 'nose_width',
    label: 'Nasenbreite',
    category: 'features',
    description: 'Breite der Nasenflügel relativ zur Gesichtsbreite.',
    howMeasured: 'Abstand der Flügelränder / Gesichtsbreite.',
    whyImportant: 'Beeinflusst Midface-Balance.',
    normRange: '0,20–0,26',
    unit: 'ratio',
  },
  {
    id: 'nose_length',
    label: 'Nasenlänge',
    category: 'features',
    description: 'Länge von Nasenwurzel bis Spitze.',
    howMeasured: 'Vertikale Distanz relativ zur Gesichtshöhe.',
    whyImportant: 'Wichtig für Midface-Proportionen.',
    normRange: '0,20–0,24',
    unit: 'ratio',
  },
  {
    id: 'nose_symmetry',
    label: 'Nasensymmetrie',
    category: 'symmetry',
    description: 'Achse und Flügelsymmetrie der Nase.',
    howMeasured: 'Abweichung der Nasenachse von der Gesichtsmitte.',
    whyImportant: 'Die Nase ist eine zentrale Achsenreferenz.',
    normRange: '±1,5° Achse',
    unit: '%',
  },
  {
    id: 'lip_shape',
    label: 'Lippenform',
    category: 'features',
    description: 'Kontur und Verhältnis von Ober- zu Unterlippe.',
    howMeasured: 'Lippenkontur-Landmarken und Höhenverhältnis.',
    whyImportant: 'Prägt die untere Gesichtsharmonie.',
    normRange: 'Unter-/Oberlippe ≈ 1,2–1,6',
    unit: 'ratio',
  },
  {
    id: 'lip_height',
    label: 'Lippenhöhe',
    category: 'features',
    description: 'Vertikale Höhe der Lippenpartie.',
    howMeasured: 'Oberlippenrand bis Unterlippenrand.',
    whyImportant: 'Beeinflusst Lippenpräsenz im Foto.',
    normRange: 'individuell, proportional zum Untergesicht',
    unit: 'mm',
  },
  {
    id: 'lip_width',
    label: 'Lippenbreite',
    category: 'features',
    description: 'Mundbreite relativ zu den Augenaußenkanten.',
    howMeasured: 'Mundwinkelabstand / interkanthaler Außenabstand.',
    whyImportant: 'Sollte zu Augen und Kiefer passen.',
    normRange: '0,90–1,10',
    unit: 'ratio',
  },
  {
    id: 'mouth_corners',
    label: 'Mundwinkel',
    category: 'symmetry',
    description: 'Höhensymmetrie der Mundwinkel in Ruhelage.',
    howMeasured: 'Vertikale Differenz der Mundwinkel-Landmarken.',
    whyImportant: 'Beeinflusst den Neutralausdruck.',
    normRange: '< 1,5 mm',
    unit: 'mm Δ',
  },
  {
    id: 'philtrum',
    label: 'Philtrum',
    category: 'features',
    description: 'Länge und Ausrichtung der Philtrum-Rinne.',
    howMeasured: 'Nasenbasis bis Oberlippenmitte.',
    whyImportant: 'Teil der Midface- und Lippenproportion.',
    normRange: 'ca. 11–15 mm (geschätzt frontal)',
    unit: 'mm',
  },
  {
    id: 'chin',
    label: 'Kinn',
    category: 'features',
    description: 'Position und Symmetrie der Kinnspitze.',
    howMeasured: 'Abweichung von der Mittelachse und relative Projektion (frontal geschätzt).',
    whyImportant: 'Schließt die untere Gesichtsachse ab.',
    normRange: '< 2 mm seitliche Abweichung',
    unit: '%',
  },
  {
    id: 'jaw',
    label: 'Kiefer',
    category: 'features',
    description: 'Kieferbreite und Winkelbalance.',
    howMeasured: 'Kieferwinkel und Breite relativ zur Jochbeinbreite.',
    whyImportant: 'Definiert die untere Gesichtsstruktur.',
    normRange: 'Breitenratio 0,85–1,05',
    unit: '%',
  },
  {
    id: 'jawline',
    label: 'Jawline',
    category: 'features',
    description: 'Konturschärfe und Definition der Kieferlinie im Foto.',
    howMeasured: 'Kontrast und Verlauf der Unterkieferkontur (fotoabhängig).',
    whyImportant: 'Stark licht- und winkelabhängig – kein Knochenmaß.',
    normRange: 'gute Kontur unter weichem Seitenlicht',
    unit: 'score',
  },
  {
    id: 'cheekbones',
    label: 'Wangenknochen',
    category: 'features',
    description: 'Prominenz und Symmetrie der Jochbögen.',
    howMeasured: 'Höchste Jochbeinpunkte links/rechts und Breite.',
    whyImportant: 'Formt Midface-Volumen und Lichtführung.',
    normRange: 'hohe Symmetrie der Höhenpunkte',
    unit: '%',
  },
  {
    id: 'midface_ratio',
    label: 'Midface Ratio',
    category: 'proportions',
    description: 'Anteil des Mittelgesichts an der Gesamthöhe.',
    howMeasured: 'Brauen–Nasenbasis / gesamte Gesichtshöhe.',
    whyImportant: 'Klassisches Proportionsmaß.',
    normRange: 'ca. 0,30–0,36',
    unit: 'ratio',
  },
  {
    id: 'lower_face_ratio',
    label: 'Lower Face Ratio',
    category: 'proportions',
    description: 'Anteil des Untergesichts.',
    howMeasured: 'Nasenbasis–Kinn / Gesichtshöhe.',
    whyImportant: 'Beeinflusst Kiefer- und Kinnwirkung.',
    normRange: 'ca. 0,33–0,38',
    unit: 'ratio',
  },
  {
    id: 'fwhr',
    label: 'Facial Width-Height Ratio',
    category: 'proportions',
    description: 'Verhältnis Jochbeinbreite zu oberer Gesichtshöhe.',
    howMeasured: 'Bizygomatische Breite / Höhe Brauen–Oberlippe.',
    whyImportant: 'Häufig in der Forschung genutztes Maß – kein Attraktivitätsurteil.',
    normRange: 'ca. 1,7–2,1 (variabel)',
    unit: 'fWHR',
  },
  {
    id: 'chin_projection',
    label: 'Chin Projection',
    category: 'proportions',
    description: 'Relative Kinnprojektion – frontal nur geschätzt.',
    howMeasured: 'Abschätzung über Untergesichtsverhältnisse (kein echtes Profil).',
    whyImportant: 'Für präzise Werte wäre eine Seitenaufnahme nötig.',
    normRange: 'orientierend, profilabhängig',
    unit: 'score',
  },
  {
    id: 'face_shape',
    label: 'Gesichtsform',
    category: 'proportions',
    description: 'Klassifikation anhand von Stirn-, Jochbein- und Kieferbreiten.',
    howMeasured: 'Breitenverhältnisse und Höhenprofil.',
    whyImportant: 'Hilft bei Frisur- und Brillenvorschlägen.',
    normRange: 'oval / herz / rund / eckig / diamant (individuell)',
    unit: 'type',
  },
  {
    id: 'head_tilt',
    label: 'Kopfneigung',
    category: 'photo',
    description: 'Abweichung der Kopfhaltung von der Frontalachse.',
    howMeasured: 'Augenachse und Gesichtsmitte relativ zum Bildrahmen.',
    whyImportant: 'Schiefe Aufnahmen verfälschen Symmetriemessungen.',
    normRange: '< 3°',
    unit: '°',
  },
  {
    id: 'face_midline',
    label: 'Gesichtsmitte',
    category: 'symmetry',
    description: 'Ausrichtung von Stirn, Nase und Kinn auf einer Achse.',
    howMeasured: 'Regression der zentralen Landmarken.',
    whyImportant: 'Grundlage für Symmetrieanalysen.',
    normRange: '> 90 % Achsenkohärenz',
    unit: '%',
  },
  {
    id: 'skin_evenness',
    label: 'Hautgleichmäßigkeit',
    category: 'skin',
    description: 'Relative Gleichmäßigkeit von Ton und Textur im Foto.',
    howMeasured: 'Lokale Kontrast- und Farbvarianz (fotoabhängig).',
    whyImportant: 'Stark von Licht, Make-up und Auflösung beeinflusst.',
    normRange: 'gleichmäßig unter weichem Licht',
    unit: 'score',
  },
  {
    id: 'lighting_quality',
    label: 'Lichtqualität',
    category: 'photo',
    description: 'Gleichmäßigkeit und Richtung der Beleuchtung.',
    howMeasured: 'Helligkeitsverteilung über Stirn, Wangen und Kinn.',
    whyImportant: 'Schlechtes Licht verzerrt Konturen und Hautwerte.',
    normRange: 'weiches Frontallicht ohne harte Schatten',
    unit: 'score',
  },
];

export const EXERCISES: Exercise[] = [
  {
    id: 'chin_tucks',
    title: 'Chin Tucks',
    category: 'posture',
    duration: '5–8 Wiederholungen',
    frequency: '2–3× täglich',
    evidence: 'well_supported',
    evidenceNote: 'Haltungstraining ist gut belegt für Nackenstellung; ändert keine Knochenstruktur.',
    steps: [
      'Sitz oder Stand, Blick geradeaus.',
      'Kinn leicht nach hinten und unten ziehen (Doppelkinn-Gefühl).',
      '2–3 Sekunden halten, entspannen.',
      'Schultern locker lassen.',
    ],
    relatedMetrics: ['head_tilt', 'jawline', 'chin', 'posture_head', 'neckline'],
  },
  {
    id: 'neck_stretch',
    title: 'Neck Stretch',
    category: 'posture',
    duration: '20–30 Sek. je Seite',
    frequency: 'täglich',
    evidence: 'well_supported',
    evidenceNote: 'Dehnung kann Verspannungen lindern; kein Einfluss auf Gesichtsproportionen.',
    steps: [
      'Kopf langsam zur Seite neigen.',
      'Leichter Zug mit der Hand optional.',
      'Rücken gerade, nicht in die Schulter ziehen.',
      'Seite wechseln.',
    ],
    relatedMetrics: ['head_tilt', 'jaw', 'posture_head'],
  },
  {
    id: 'upper_back_mobility',
    title: 'Upper Back Mobility',
    category: 'posture',
    duration: '5 Minuten',
    frequency: 'täglich',
    evidence: 'well_supported',
    evidenceNote: 'Thoraxmobilität unterstützt aufrechte Haltung und Foto-Wirkung.',
    steps: [
      'Offene Arme, Brust leicht öffnen.',
      'Langsame Rotation im oberen Rücken.',
      'Atmung ruhig und tief.',
      'Keine Schmerzen erzwingen.',
    ],
    relatedMetrics: ['head_tilt', 'jawline', 'posture_head', 'neckline'],
  },
  {
    id: 'face_relax',
    title: 'Gesicht entspannen',
    category: 'face',
    duration: '2 Minuten',
    frequency: 'bei Anspannung',
    evidence: 'general_advice',
    evidenceNote: 'Allgemeine Entspannungshilfe; keine Belege für Strukturveränderung.',
    steps: [
      'Augen sanft schließen.',
      'Kiefer lösen, Zunge entspannen.',
      'Stirn und Brauen bewusst lockern.',
      'Langsam ausatmen.',
    ],
    relatedMetrics: ['eyebrows', 'mouth_corners', 'jaw', 'mandible'],
  },
  {
    id: 'expression_control',
    title: 'Mimik-Kontrolle',
    category: 'face',
    duration: '3 Minuten',
    frequency: 'vor Fotos',
    evidence: 'general_advice',
    evidenceNote: 'Hilft für neutrale Aufnahmen; verändert keine Anatomie.',
    steps: [
      'Neutralen Ausdruck im Spiegel finden.',
      'Mundwinkel weich halten.',
      'Augen entspannt öffnen.',
      'Kopf gerade ausrichten.',
    ],
    relatedMetrics: ['mouth_corners', 'eye_height', 'head_tilt'],
  },
  {
    id: 'jaw_rest',
    title: 'Unterkiefer-Ruheposition',
    category: 'jaw',
    duration: 'Gewohnheit',
    frequency: 'tagsüber',
    evidence: 'general_advice',
    evidenceNote: 'Allgemeiner Haltungshinweis; ersetzt keine zahnmedizinische Beratung.',
    steps: [
      'Zähne leicht auseinander.',
      'Lippen geschlossen.',
      'Zungenspitze leicht am Gaumen (wenn angenehm).',
      'Nicht zusammenbeißen.',
    ],
    relatedMetrics: ['jaw', 'jawline', 'chin', 'jaw_angle', 'mandible'],
  },
  {
    id: 'nasal_breathing',
    title: 'Nasenatmung fördern',
    category: 'breathing',
    duration: '5 Minuten',
    frequency: 'täglich',
    evidence: 'well_supported',
    evidenceNote: 'Nasenatmung ist allgemein empfohlen; bei Beschwerden ärztlich abklären.',
    steps: [
      'Durch die Nase einatmen.',
      'Ruhig und gleichmäßig ausatmen.',
      'Mund geschlossen halten, wenn möglich.',
      'Bei Behinderung HNO/Arzt fragen.',
    ],
    relatedMetrics: ['jaw', 'mouth_corners'],
  },
];

export const TIPS_BY_METRIC: Record<string, string[]> = {
  jawline: [
    'Weiches Seitenlicht betont Konturen auf Fotos.',
    'Aufrechte Haltung und Kamerawinkel auf Augenhöhe.',
    'Bartstile können die Kieferlinie optisch rahmen.',
    'Frisuren mit Volumen oben können Proportionen ausgleichen.',
    'Körperfettanteil kann die Kontursichtbarkeit beeinflussen – ohne Diätversprechen.',
  ],
  eye_height: [
    'Ausreichend Schlaf kann Schwellungen reduzieren.',
    'Gleichmäßiges Frontallicht vermeidet falsche Asymmetrien.',
    'Augenbrauenpflege rahmt den Blick.',
  ],
  eye_spacing: [
    'Brillengestelle an Gesichtsbreite anpassen.',
    'Fransen/Pony können den Fokus verschieben – bewusst wählen.',
  ],
  canthal_tilt: [
    'Neutraler Blick ohne zusammengekniffene Augen.',
    'Kamera nicht von unten fotografieren.',
  ],
  eyebrows: [
    'Sanfte Formung statt asymmetrischer Überkorrektur.',
    'Beide Brauen im gleichen Abstand zur Lidfalte halten.',
  ],
  skin_evenness: [
    'Täglicher SPF bei Tageslicht.',
    'Milde Reinigung und Feuchtigkeitspflege.',
    'Niacinamid / Vitamin C sind gängige Pflegeoptionen – bei Unsicherheit Hautärztin fragen.',
    'Bei Hautproblemen dermatologische Abklärung.',
  ],
  lip_shape: [
    'Lippenpflege und ausreichende Flüssigkeitszufuhr.',
    'Neutrale Lippen ohne starkes Pressen fotografieren.',
  ],
  lip_height: [
    'Lippenbalsam vor dem Foto.',
    'Nicht die Lippen einrollen oder fest pressen.',
  ],
  lighting_quality: [
    'Fensterlicht von vorne oder 45°-Seite.',
    'Harte Deckenstrahler vermeiden.',
    'Abstand Kamera–Gesicht ca. 60–90 cm.',
  ],
  head_tilt: [
    'Beide Ohren etwa gleich hoch im Bild.',
    'Nacken lang, Kinn leicht parallel zum Boden.',
  ],
  chin: [
    'Kinn leicht nach vorne (nicht nach oben) für klarere Kontur im Foto.',
    'Haltung vor dem Spiegel üben.',
  ],
  jaw: [
    'Nicht zusammenbeißen während der Aufnahme.',
    'Entspannte Kieferruheposition.',
  ],
  nose_symmetry: [
    'Frontal und gerade fotografieren – seitliches Licht verzerrt.',
  ],
  face_symmetry: [
    'Kleine Asymmetrien sind normal.',
    'Vergleiche nur Aufnahmen unter ähnlichem Licht.',
  ],
  forehead: [
    'Frisuren können Stirnanteil optisch verändern.',
  ],
  cheekbones: [
    'Weiches Seitenlicht kann Jochbögen betonen.',
  ],
  philtrum: [
    'Neutraler Mundschluss, kein übertriebenes Lächeln für Messfotos.',
  ],
  mouth_corners: [
    'Weicher Neutralausdruck statt erzwungenem Lächeln.',
  ],
  face_shape: [
    'Frisur und Brille an die Gesichtsform anpassen.',
  ],
  golden_ratio: [
    'Ein Orientierungswert – keine Idealnorm für jedes Gesicht.',
  ],
  facial_thirds: [
    'Frisuren und Bart können Drittel optisch ausgleichen.',
  ],
  facial_fifths: [
    'Brillenbreite an den Fünfteln ausrichten.',
  ],
  midface_ratio: [
    'Licht und Kamerahöhe nicht von unten wählen.',
  ],
  lower_face_ratio: [
    'Haltung und Kamerawinkel prüfen, bevor du Vergleiche ziehst.',
  ],
  fwhr: [
    'fWHR ist ein Forschungsmaß, kein Attraktivitätsscore.',
  ],
  chin_projection: [
    'Für belastbare Einschätzung wäre ein Profilfoto nötig.',
  ],
  face_midline: [
    'Kopf gerade, Kamera auf Augenhöhe.',
  ],
  nose_width: [
    'Frontales Weichlicht, kein extremes Weitwinkel nah am Gesicht.',
  ],
  nose_length: [
    'Kamera nicht zu nah und nicht von unten.',
  ],
  lip_width: [
    'Entspannter Mund, natürliche Breite.',
  ],
  eye_angle: [
    'Beide Augen gleichmäßig öffnen, kein Schielen ins Licht.',
  ],
  jaw_angle: [
    'Weiches Seitenlicht für Konturvergleiche.',
    'Entspannte Kieferruhe – nicht zusammenbeißen.',
  ],
  face_width: [
    'Kamera auf Augenhöhe, kein extremes Weitwinkel nah am Gesicht.',
  ],
  face_depth: [
    '360°-Scan unter gleichmäßigem Licht wiederholen.',
  ],
  side_profile: [
    'Schultern entspannen, Blick gerade bei Seitenposen.',
  ],
  nose_profile: [
    'Seitenlicht weich halten – harte Schatten verzerren.',
  ],
  posture_head: [
    'Chin Tucks und Nackenmobilität für aufrechte Haltung.',
    'Bildschirm auf Augenhöhe – nicht nach unten schauen.',
  ],
  mandible: [
    'Haltung und Kamerawinkel prüfen vor Vergleichen.',
  ],
  maxilla: [
    'Nur Orientierungswert aus dem Mehrwinkel-Scan.',
  ],
  neckline: [
    'Kinn leicht nach vorne (nicht nach oben) im Foto.',
    'Aufrechte Haltung betont den Kinn–Hals-Übergang optisch.',
  ],
};
